import { mkdirSync, openSync, writeSync, closeSync, unlinkSync } from "node:fs";
import { constants } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

/** tmux server socket name. Global per OS user by default, so concurrent
 *  Passage daemons (e.g. separate checkouts) MUST scope it: derive
 *  `passage-<hash(data-root)>` at boot via {@link setTmuxSocketName} (or
 *  `PASSAGE_TMUX_SOCKET` to override). Sharing a server means sharing
 *  sessions, and each daemon's boot sweep reaps what it cannot map. */
let activeSocketName = process.env.PASSAGE_TMUX_SOCKET ?? "passage";
export function setTmuxSocketName(name: string): void {
  activeSocketName = name;
}
export function tmuxSocketName(): string {
  return activeSocketName;
}
export const TMUX_SESSION_PREFIX = "passage-";
export const TMUX_CONF_PATH = join(tmpdir(), "passage-tmux.conf");

const TMUX_CONF_LINES = [
  "# Generated by Passage. Isolated server: user tmux.conf is never loaded.",
  "set -g status off",
  "set -g escape-time 0",
  "set -g history-limit 50000",
  "set -g focus-events on",
  "set -g allow-passthrough on",
  "set -g set-clipboard on",
  'set -g default-terminal "xterm-256color"',
  "set -gw aggressive-resize on",
  // Dead panes persist so fast one-shots (echo, build steps) survive long
  // enough to attach, capture output, and read #{pane_dead_status}.
  // Cleanup is always explicit via kill-session; nothing auto-reaps.
  "set -g remain-on-exit on",
];

let confEnsured = false;

/** tmux is a hard requirement. No fallback to direct PTY spawn. */
export function ensureTmuxAvailable(): void {
  let found: string | null = null;
  try {
    found = Bun.which("tmux");
  } catch {
    found = null;
  }
  if (!found) {
    throw new Error(
      "tmux is required for Passage terminals but was not found on PATH. Install tmux (e.g. `brew install tmux` / `sudo apt-get install tmux`).",
    );
  }
  // `new-session -e` (per-session env, tmux 3.2+) is how service variables
  // reach the shell; `allow-passthrough` below needs tmux 3.3+.
  try {
    const proc = Bun.spawnSync(["tmux", "-V"], { stdout: "pipe", stderr: "pipe" });
    const match = /tmux (\d+)\.(\d+)/.exec(proc.stdout?.toString() ?? "");
    const major = Number(match?.[1]);
    const minor = Number(match?.[2]);
    if (!Number.isSafeInteger(major) || major < 3 || (major === 3 && (!Number.isSafeInteger(minor) || minor < 3))) {
      throw new Error(
        `tmux 3.3+ is required for Passage terminals (found ${match?.[0] ?? "unknown version"}).`,
      );
    }
  } catch (err) {
    if (err instanceof Error && err.message.includes("tmux 3.3+")) throw err;
    // Version probe failure is non-fatal; session creation will surface it.
  }
}

/** Vars that must never reach a session shell: daemon routing, Passage
 *  config, and tmux nesting markers. Scrubbed from the child (`env -u`)
 *  and from the long-lived server global at boot, so stale values from
 *  previous daemon runs cannot leak in through either path. */
export function tmuxStrippedEnvNames(): string[] {
  const names = new Set(["PORT", "PASEO_PORT", "TMUX", "TMUX_PANE"]);
  for (const key of Object.keys(process.env)) {
    if (key.startsWith("PASSAGE_")) names.add(key);
  }
  return [...names];
}

/** Write the isolated tmux conf (user ~/.tmux.conf is never loaded when -f is passed).
 *
 *  The path is world-predictable (/tmp), so the write uses O_NOFOLLOW and
 *  0600: a pre-planted symlink can neither redirect the write nor be
 *  followed. Write failures propagate with the path -- a missing conf must
 *  fail terminal creation loudly, not surface later as a tmux error. */
function writeConfFile(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const attempt = () => {
    const fd = openSync(path, constants.O_WRONLY | constants.O_CREAT | constants.O_TRUNC | constants.O_NOFOLLOW, 0o600);
    try {
      writeSync(fd, content);
    } finally {
      closeSync(fd);
    }
  };
  try {
    attempt();
  } catch (err) {
    if ((err as NodeJS.ErrnoException)?.code === "ELOOP") {
      unlinkSync(path);
      attempt();
    } else {
      throw err;
    }
  }
}

export function ensureTmuxConf(): string {
  if (!confEnsured) {
    try {
      writeConfFile(TMUX_CONF_PATH, TMUX_CONF_LINES.join("\n") + "\n");
    } catch (err) {
      throw new Error(`cannot write tmux conf ${TMUX_CONF_PATH}: ${err instanceof Error ? err.message : String(err)}`);
    }
    confEnsured = true;
  }
  // The server outlives Passage, so a conf written after server creation is
  // never read. Re-apply the options that must be live (idempotent), and
  // scrub stripped vars from the server-global env so sessions created
  // before/around upgrades cannot inherit them.
  try {
    tmuxRun(["set", "-g", "remain-on-exit", "on"]);
    for (const name of tmuxStrippedEnvNames()) {
      tmuxRun(["set-environment", "-g", "-u", name]);
    }
  } catch {}
  return TMUX_CONF_PATH;
}

export function tmuxSessionName(terminalId: string): string {
  return `${TMUX_SESSION_PREFIX}${terminalId}`;
}

/** Metadata keys persisted as tmux session user options (@passage-*).
 *  The tmux server outlives Passage, so this is the restart-recovery store:
 *  no sqlite row to go stale, and kill-session cleans it up automatically. */
export const TMUX_META_KEYS = ["workspace", "title", "cwd", "cols", "rows", "created"] as const;
export type TmuxSessionMeta = Record<(typeof TMUX_META_KEYS)[number], string> & {
  /** `workspaceId:scriptName` for service sessions. Absent for interactive
   *  terminals and one-shots; lets the scripts service reconcile orphaned
   *  starts (created-then-crashed before the sqlite row existed). */
  script?: string;
};

function baseArgs(): string[] {
  return ["-L", activeSocketName];
}

export type TmuxResult = { status: number; stdout: string; stderr: string };

export function tmuxRun(args: string[], env?: Record<string, string | undefined>): TmuxResult {
  const proc = Bun.spawnSync(["tmux", ...baseArgs(), ...args], {
    env: env as Record<string, string>,
    stdout: "pipe",
    stderr: "pipe",
  });
  return {
    status: proc.exitCode ?? 1,
    stdout: proc.stdout?.toString() ?? "",
    stderr: proc.stderr?.toString() ?? "",
  };
}

/** Create the session detached running `shellArgv` in `cwd`, or no-op when it already exists.
 *
 * Env handling is explicit because tmux sessions do NOT inherit arbitrary
 * client env (only `update-environment` vars propagate). Defined entries
 * become `new-session -e KEY=VALUE` (exact session env); the stripped set
 * (`tmuxStrippedEnvNames`) is force-unset via an `env -u` prefix AND
 * scrubbed from the server global at boot, so stale values from previous
 * daemon runs cannot leak in. Kept short deliberately: doubling the full
 * env onto the command line exceeds tmux's command-length limit.
 *
 * Metadata is chained into the same tmux invocation (`;` separates tmux
 * commands; it is only special as a standalone argv element, so `;`
 * inside the child argv is safe) so there is no crash window between
 * session creation and metadata write. */
export function tmuxEnsureDetachedSession(
  terminalId: string,
  shellArgv: string[],
  cwd: string,
  cols: number,
  rows: number,
  env: Record<string, string | undefined>,
  meta?: TmuxSessionMeta,
): void {
  ensureTmuxAvailable();
  const conf = ensureTmuxConf();
  const name = tmuxSessionName(terminalId);
  if (tmuxRun(["has-session", "-t", name]).status === 0) return;
  const envFlags: string[] = [];
  // Scrubbed unless the session env defines them explicitly (service
  // ports): explicit entries win via -e below, inherited/stale ones die.
  const unsetNames = new Set<string>();
  for (const name of tmuxStrippedEnvNames()) {
    if (!(name in env)) unsetNames.add(name);
  }
  for (const [key, value] of Object.entries(env)) {
    if (value === undefined) unsetNames.add(key);
    else envFlags.push("-e", `${key}=${value}`);
  }
  const wrappedArgv = ["env", ...[...unsetNames].flatMap((k) => ["-u", k]), ...shellArgv];
  // Metadata is chained into the same tmux invocation so there is no crash
  // window between session creation and metadata write. Argv array passes
  // values literally, so titles/cwds with spaces survive round-trip.
  const metaChain: string[] =
    meta !== undefined
      ? Object.entries(meta).flatMap(([key, value]) => [";", "set-option", "-t", name, `@passage-${key}`, value])
      : [];
  const res = Bun.spawnSync(
    ["tmux", ...baseArgs(), "-f", conf, "new-session", "-d", "-s", name, "-x", String(cols), "-y", String(rows), "-c", cwd, ...envFlags, "--", ...wrappedArgv, ...metaChain],
    { env: env as Record<string, string>, stdout: "pipe", stderr: "pipe" },
  );
  const status = res.exitCode ?? 1;
  if (status !== 0) {
    const stderr = res.stderr?.toString() ?? "";
    throw new Error(`tmux new-session failed for ${name}: ${stderr.trim() || `exit ${status}`}`);
  }
}

export function tmuxHasSession(terminalId: string): boolean {
  return tmuxRun(["has-session", "-t", tmuxSessionName(terminalId)]).status === 0;
}

export function tmuxKillSession(terminalId: string): boolean {
  const res = tmuxRun(["kill-session", "-t", tmuxSessionName(terminalId)]);
  if (res.status === 0) return true;
  // "no such session" also satisfies teardown: only report failure when
  // the session demonstrably survives.
  return !tmuxHasSession(terminalId);
}

/** Current visible pane content (with ANSI), for instant rehydrate on reattach. Null when no session. */
export function tmuxCapturePane(terminalId: string, lines = 5000): string | null {
  const res = tmuxRun(["capture-pane", "-p", "-e", "-t", tmuxSessionName(terminalId), "-S", `-${lines}`]);
  if (res.status !== 0) return null;
  return res.stdout;
}

/** All Passage-owned tmux session terminal IDs on this server (for orphan recovery). */
export function tmuxListTerminalIds(): string[] {
  const res = tmuxRun(["list-sessions", "-F", "#{session_name}"]);
  if (res.status !== 0) return [];
  return res.stdout
    .split("\n")
    .map((s) => s.trim())
    .filter((s) => s.startsWith(TMUX_SESSION_PREFIX))
    .map((s) => s.slice(TMUX_SESSION_PREFIX.length));
}

/** Update one metadata item (e.g. dims after a lease-holder resize). */
export function tmuxSetSessionMetaItem(terminalId: string, key: string, value: string): boolean {
  return tmuxRun(["set-option", "-t", tmuxSessionName(terminalId), `@passage-${key}`, value]).status === 0;
}

/** Metadata for a Passage-owned session. Null when the session is gone or
 *  carries no Passage metadata (e.g. one-shot script sessions, which are
 *  intentionally anonymous so the boot sweep reaps them). `script` is
 *  best-effort: absent for interactive terminals, never nulls the result. */
export function tmuxGetSessionMeta(terminalId: string): TmuxSessionMeta | null {
  const meta = {} as TmuxSessionMeta;
  for (const key of TMUX_META_KEYS) {
    const res = tmuxRun(["show-options", "-t", tmuxSessionName(terminalId), "-v", `@passage-${key}`]);
    if (res.status !== 0) return null;
    const value = res.stdout.replace(/\n$/, "");
    if (value.length === 0) return null;
    meta[key] = value;
  }
  const script = tmuxRun(["show-options", "-t", tmuxSessionName(terminalId), "-v", "@passage-script"]);
  if (script.status === 0) {
    const value = script.stdout.replace(/\n$/, "");
    if (value.length > 0) meta.script = value;
  }
  return meta;
}

/** One batched pane-state query for every session on our server. Sessions
 *  absent from the map are gone (killed). Prefer this over per-terminal
 *  `list-panes` so N terminals cost one subprocess per poll tick. */
export type TmuxPaneStates = Map<string, { dead: boolean; exitStatus: number | null }>;
export function tmuxListPaneStates(): TmuxPaneStates {
  const states: TmuxPaneStates = new Map();
  const res = tmuxRun(["list-panes", "-a", "-F", "#{session_name}\t#{pane_dead}\t#{pane_dead_status}"]);
  if (res.status !== 0) return states;
  for (const line of res.stdout.split("\n")) {
    const [session, deadFlag, statusRaw] = line.split("\t");
    if (!session?.startsWith(TMUX_SESSION_PREFIX)) continue;
    const parsed = Number(statusRaw);
    states.set(session.slice(TMUX_SESSION_PREFIX.length), {
      dead: deadFlag === "1",
      exitStatus: deadFlag === "1" && Number.isSafeInteger(parsed) ? parsed : null,
    });
  }
  return states;
}

/** Dead/alive state of a session's (single) pane. Null when no such session. */
export function tmuxPaneState(terminalId: string): { dead: boolean; exitStatus: number | null } | null {
  const res = tmuxRun(["list-panes", "-t", tmuxSessionName(terminalId), "-F", "#{pane_dead} #{pane_dead_status}"]);
  if (res.status !== 0) return null;
  const line = res.stdout.trim().split("\n")[0] ?? "";
  const [deadFlag, statusRaw] = line.trim().split(/\s+/);
  if (deadFlag === undefined) return null;
  const dead = deadFlag === "1";
  const parsed = Number(statusRaw);
  return { dead, exitStatus: dead && Number.isSafeInteger(parsed) ? parsed : null };
}

/** Argv for the tmux client that attaches the Passage PTY to the session. */
export function tmuxAttachArgv(terminalId: string): string[] {
  return ["tmux", ...baseArgs(), "attach-session", "-t", tmuxSessionName(terminalId)];
}
