import { afterEach, describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { GitError, GitService } from "./git.ts";

const roots: string[] = [];
const git = async (cwd: string, ...args: string[]) => { const p = Bun.spawn(["git", "-C", cwd, ...args], { stdout: "pipe", stderr: "pipe" }); if (await p.exited !== 0) throw new Error(await new Response(p.stderr).text()); };
const gitOutput = async (cwd: string, ...args: string[]) => { const p = Bun.spawn(["git", "-C", cwd, ...args], { stdout: "pipe", stderr: "pipe" }); const [out, err, code] = await Promise.all([new Response(p.stdout).text(), new Response(p.stderr).text(), p.exited]); if (code !== 0) throw new Error(err); return out; };
const fixture = async () => { const root = await mkdtemp(join(tmpdir(), "passage-git-")); roots.push(root); await git(root, "init", "-b", "main"); await git(root, "config", "user.email", "test@example.com"); await git(root, "config", "user.name", "Test"); return root; };
afterEach(async () => { await Promise.all(roots.splice(0).map((r) => rm(r, { recursive: true, force: true }))); });

describe("GitService", () => {
  test("discovers main checkout and linked worktree", async () => { const root = await fixture(); await writeFile(join(root, "file with spaces"), "one\n"); await git(root, "add", "."); await git(root, "commit", "-m", "initial"); const service = new GitService(); expect((await service.discover(root)).checkoutRoot).toBe(root); const wt = join(root, "linked worktree"); await git(root, "worktree", "add", "-b", "linked", wt); const d = await service.discover(wt); expect(d.checkoutRoot).toBe(wt); expect(d.mainCheckoutRoot).toBe(root); });
  test("normalizes paths, rename, untracked, detached and ahead/behind", async () => { const root = await fixture(); await writeFile(join(root, "old name"), "x\n"); await git(root, "add", "."); await git(root, "commit", "-m", "initial"); await git(root, "mv", "old name", "new name"); await writeFile(join(root, "untracked file"), "u"); const s = await new GitService().status(root); expect(s.files.map((f) => f.kind)).toEqual(expect.arrayContaining(["renamed", "untracked"])); await git(root, "commit", "-am", "rename"); await git(root, "checkout", "--detach", "HEAD"); expect((await new GitService().discover(root)).detached).toBe(true); });
  test("returns structured binary and hunks", async () => { const root = await fixture(); await writeFile(join(root, "a.txt"), "one\ntwo\n"); await git(root, "add", "."); await git(root, "commit", "-m", "initial"); await writeFile(join(root, "a.txt"), "one\nthree\n"); const diffs = await new GitService().diff(root); expect(diffs[0].hunks[0].lines.some((x) => x.kind === "added")).toBe(true); });
  test("lists linked worktrees via porcelain", async () => {
    const root = await fixture();
    await writeFile(join(root, "file.txt"), "hello\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    const service = new GitService();
    const wt = join(root, "linked-wt");
    await git(root, "worktree", "add", "-b", "feature-x", wt);
    const list = await service.listWorktrees(root);
    expect(list.length).toBe(2);
    expect(list.some((w) => w.branchRef === "main")).toBe(true);
    expect(list.some((w) => w.branchRef === "feature-x")).toBe(true);
  });
  test("honors cancellation, limits, and git failures", async () => { const root = await fixture(); const service = new GitService(); const controller = new AbortController(); controller.abort(); await expect(service.status(root, { signal: controller.signal })).rejects.toBeInstanceOf(GitError); await expect(service.status(join(root, "missing"))).rejects.toBeInstanceOf(GitError); const r = await service.diff(root, "working-tree", { maxOutputBytes: 2 }); expect(r[0]?.oversized ?? true).toBe(true); });
  test("renders untracked files as add-only diffs in the working tree", async () => {
    const root = await fixture();
    await writeFile(join(root, "tracked.txt"), "one\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    await writeFile(join(root, "new-file.txt"), "alpha\nbeta\n");
    const diffs = await new GitService().diff(root, "working-tree");
    const untracked = diffs.find((d) => d.path === "new-file.txt");
    expect(untracked).toBeDefined();
    expect(untracked?.additions).toBe(2);
    expect(untracked?.deletions).toBe(0);
    expect(untracked?.hunks.length).toBeGreaterThan(0);
    expect(untracked?.hunks[0].lines.every((l) => l.kind === "added")).toBe(true);
  });
  test("omits untracked diffs from the staged target", async () => {
    const root = await fixture();
    await writeFile(join(root, "tracked.txt"), "one\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    await writeFile(join(root, "new-file.txt"), "alpha\n");
    const diffs = await new GitService().diff(root, "staged");
    expect(diffs.find((d) => d.path === "new-file.txt")).toBeUndefined();
  });
  test("marks binary and oversized untracked files without reading full contents", async () => {
    const root = await fixture();
    await writeFile(join(root, "tracked.txt"), "one\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    await writeFile(join(root, "blob.bin"), Buffer.from([0x00, 0x01, 0x02]));
    const diffs = await new GitService().diff(root, "working-tree");
    expect(diffs.find((d) => d.path === "blob.bin")?.binary).toBe(true);
  });
  test("stages and unstages single paths and everything", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "a.txt"), "a\n");
    await writeFile(join(root, "b.txt"), "b\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    await writeFile(join(root, "a.txt"), "a2\n");
    await writeFile(join(root, "c.txt"), "c\n");
    await expect(service.stage(root, [])).rejects.toBeInstanceOf(GitError);
    await service.stage(root, ["a.txt"]);
    let s = await service.status(root);
    expect(s.files.find((f) => f.path === "a.txt")?.staged).toBe(true);
    expect(s.files.find((f) => f.path === "c.txt")?.staged).toBe(false);
    await service.unstage(root, ["a.txt"]);
    s = await service.status(root);
    expect(s.files.find((f) => f.path === "a.txt")?.staged).toBe(false);
    await service.stageAll(root);
    s = await service.status(root);
    expect(s.files.length).toBeGreaterThan(0);
    expect(s.files.every((f) => f.staged)).toBe(true);
    expect(s.files.find((f) => f.path === "c.txt")?.staged).toBe(true);
    await service.unstageAll(root);
    s = await service.status(root);
    expect(s.files.some((f) => f.staged)).toBe(false);
  });
  test("stages deletions by path", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "gone.txt"), "x\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    await rm(join(root, "gone.txt"));
    await service.stage(root, ["gone.txt"]);
    const s = await service.status(root);
    expect(s.files.find((f) => f.path === "gone.txt")?.kind).toBe("deleted");
    expect(s.files.find((f) => f.path === "gone.txt")?.staged).toBe(true);
  });
  test("discards tracked modifications, staged changes, and untracked files", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "keep.txt"), "v1\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    await writeFile(join(root, "keep.txt"), "v2\n");
    await writeFile(join(root, "scratch.txt"), "tmp\n");
    expect(await service.discard(root, "keep.txt")).toBe("restored");
    expect(await service.discard(root, "scratch.txt")).toBe("removed");
    const s = await service.status(root);
    expect(s.dirty).toBe(false);
    await writeFile(join(root, "keep.txt"), "v3\n");
    await service.stage(root, ["keep.txt"]);
    await writeFile(join(root, "keep.txt"), "v4\n");
    expect(await service.discard(root, "keep.txt")).toBe("restored");
    expect((await service.status(root)).dirty).toBe(false);
  });
  test("refuses to discard directories and unmerged paths", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "base.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    await expect(service.discard(root, "")).rejects.toBeInstanceOf(GitError);
    await expect(service.discard(root, "missing.txt")).rejects.toBeInstanceOf(GitError);
    await mkdir(join(root, "adir"));
    await writeFile(join(root, "adir", "x.txt"), "x\n");
    await expect(service.discard(root, "adir")).rejects.toBeInstanceOf(GitError);
    await git(root, "checkout", "-b", "feature");
    await writeFile(join(root, "base.txt"), "feature\n");
    await git(root, "commit", "-am", "feature change");
    await git(root, "checkout", "main");
    await writeFile(join(root, "base.txt"), "main\n");
    await git(root, "commit", "-am", "main change");
    await git(root, "merge", "feature").catch(() => {});
    await expect(service.discard(root, "base.txt")).rejects.toBeInstanceOf(GitError);
  });
  test("commits staged changes and returns the new HEAD", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "a.txt"), "a\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    await expect(service.commit(root, "   ")).rejects.toBeInstanceOf(GitError);
    await expect(service.commit(root, "empty")).rejects.toBeInstanceOf(GitError);
    await writeFile(join(root, "a.txt"), "a2\n");
    await service.stage(root, ["a.txt"]);
    const head = await service.commit(root, "second");
    expect(head).toMatch(/^[0-9a-f]{40}$/);
    expect((await service.status(root)).dirty).toBe(false);
  });
  test("pulls and fetches against a local remote", async () => {
    const origin = await mkdtemp(join(tmpdir(), "passage-git-origin-"));
    roots.push(origin);
    await git(origin, "init", "--bare");
    const root = await mkdtemp(join(tmpdir(), "passage-git-clone-"));
    roots.push(root);
    await git(root, "init", "-b", "main");
    await git(root, "config", "user.email", "test@example.com");
    await git(root, "config", "user.name", "Test");
    await git(root, "remote", "add", "origin", origin);
    await writeFile(join(root, "a.txt"), "a\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    await git(root, "push", "-u", "origin", "main");
    const other = join(tmpdir(), `passage-git-other-${Date.now()}`);
    roots.push(other);
    await git(tmpdir(), "clone", "-b", "main", origin, other);
    await git(other, "config", "user.email", "test@example.com");
    await git(other, "config", "user.name", "Test");
    await writeFile(join(other, "b.txt"), "b\n");
    await git(other, "add", ".");
    await git(other, "commit", "-m", "from other");
    await git(other, "push", "origin", "main");
    const service = new GitService();
    await service.fetch(root);
    expect((await service.status(root)).behind).toBe(1);
    await service.pull(root);
    const s = await service.status(root);
    expect(s.behind).toBe(0);
    expect(s.files.length).toBe(0);
    expect(await readFile(join(root, "b.txt"), "utf8")).toBe("b\n");
  });
  test("pull fails without an upstream while fetch is a harmless no-op", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "a.txt"), "a\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    await expect(service.pull(root)).rejects.toBeInstanceOf(GitError);
    await service.fetch(root);
    expect((await service.status(root)).behind).toBe(0);
  });
  test("merges a linked worktree branch into main and leaves main disabled as a source", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "base.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    const worktree = join(root, "feature-worktree");
    await git(root, "worktree", "add", "-b", "feature", worktree);
    await writeFile(join(worktree, "feature.txt"), "feature\n");
    await git(worktree, "add", ".");
    await git(worktree, "commit", "-m", "feature");

    await service.mergeIntoMain(worktree);

    expect(await readFile(join(root, "feature.txt"), "utf8")).toBe("feature\n");
    await expect(service.mergeIntoMain(root)).rejects.toBeInstanceOf(GitError);
  });
  test("reports commits ahead of main for a linked worktree", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "base.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    const worktree = join(root, "feature-worktree");
    await git(root, "worktree", "add", "-b", "feature", worktree);
    expect((await service.status(worktree)).aheadOfMain).toBe(0);
    expect((await service.status(root)).aheadOfMain).toBe(0);
    await writeFile(join(worktree, "feature.txt"), "feature\n");
    await git(worktree, "add", ".");
    await git(worktree, "commit", "-m", "feature");
    expect((await service.status(worktree)).aheadOfMain).toBe(1);
    await writeFile(join(worktree, "feature.txt"), "feature two\n");
    await git(worktree, "commit", "-am", "feature two");
    expect((await service.status(worktree)).aheadOfMain).toBe(2);
  });
  test("refuses a conflicting merge without touching main", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "shared.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    const worktree = join(root, "conflicting-worktree");
    await git(root, "worktree", "add", "-b", "feature", worktree);
    await writeFile(join(worktree, "shared.txt"), "feature\n");
    await git(worktree, "commit", "-am", "feature change");
    await writeFile(join(root, "shared.txt"), "main\n");
    await git(root, "commit", "-am", "main change");

    const error = await service.mergeIntoMain(worktree).then(() => undefined, (e: unknown) => e);
    expect(error).toBeInstanceOf(GitError);
    expect((error as GitError).stderr).toContain("shared.txt");
    const status = await service.status(root);
    expect(status.conflicted).toBe(false);
    expect(status.files.find((f) => f.path === "shared.txt")).toBeUndefined();
    expect(await readFile(join(root, "shared.txt"), "utf8")).toBe("main\n");
  });
  test("rebases the branch before fast-forwarding so main stays linear", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "base.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    const worktree = join(root, "feature-worktree");
    await git(root, "worktree", "add", "-b", "feature", worktree);
    await writeFile(join(worktree, "feature.txt"), "feature\n");
    await git(worktree, "add", ".");
    await git(worktree, "commit", "-m", "feature");

    // Main advances while the feature branch is open, so the branch must be
    // replayed onto main before it can merge.
    await writeFile(join(root, "main.txt"), "main\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "main progress");

    await service.mergeIntoMain(worktree);

    expect(await readFile(join(root, "feature.txt"), "utf8")).toBe("feature\n");
    expect(await readFile(join(root, "main.txt"), "utf8")).toBe("main\n");
    // A rebase plus fast-forward leaves no merge commit behind.
    expect((await gitOutput(root, "rev-list", "--merges", "main")).trim()).toBe("");
    expect((await gitOutput(root, "rev-parse", "main")).trim()).toBe((await gitOutput(root, "rev-parse", "feature")).trim());
  });
  test("aborts a conflicted rebase and reports the conflicting files", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "shared.txt"), "A\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    const worktree = join(root, "feature-worktree");
    await git(root, "worktree", "add", "-b", "feature", worktree);
    // Feature edits then reverts the line, so merging the final branch into
    // main is clean even though replaying its middle commit onto main conflicts.
    await writeFile(join(worktree, "shared.txt"), "B\n");
    await git(worktree, "commit", "-am", "feature edit");
    await writeFile(join(worktree, "shared.txt"), "A\n");
    await git(worktree, "commit", "-am", "feature revert");
    await writeFile(join(root, "shared.txt"), "M\n");
    await git(root, "commit", "-am", "main edit");

    const mainBefore = (await gitOutput(root, "rev-parse", "main")).trim();
    const featureBefore = (await gitOutput(worktree, "rev-parse", "feature")).trim();
    const error = await service.mergeIntoMain(worktree).then(() => undefined, (e: unknown) => e);
    expect(error).toBeInstanceOf(GitError);
    expect((error as GitError).message).toContain('Could not rebase "feature" onto "main"');
    expect((error as GitError).message).toContain("shared.txt");
    // Main and the branch are left exactly where they were; no rebase in progress.
    expect((await gitOutput(root, "rev-parse", "main")).trim()).toBe(mainBefore);
    expect((await gitOutput(worktree, "rev-parse", "feature")).trim()).toBe(featureBefore);
    expect(await readFile(join(root, "shared.txt"), "utf8")).toBe("M\n");
    expect((await service.status(worktree)).conflicted).toBe(false);
  });
  test("reports behindMain when main advances past the branch point", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "base.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    const worktree = join(root, "feature-worktree");
    await git(root, "worktree", "add", "-b", "feature", worktree);
    expect((await service.status(worktree)).behindMain).toBe(0);
    await writeFile(join(root, "main.txt"), "main\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "main progress");
    expect((await service.status(worktree)).behindMain).toBe(1);
    expect((await service.status(worktree)).aheadOfMain).toBe(0);
  });
  test("replays the branch onto main via rebase", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "base.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    const worktree = join(root, "feature-worktree");
    await git(root, "worktree", "add", "-b", "feature", worktree);
    await writeFile(join(worktree, "feature.txt"), "feature\n");
    await git(worktree, "add", ".");
    await git(worktree, "commit", "-m", "feature");
    await writeFile(join(root, "main.txt"), "main\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "main progress");
    await service.rebase(worktree);
    expect((await service.status(worktree)).behindMain).toBe(0);
    expect((await service.status(worktree)).aheadOfMain).toBe(1);
  });
  test("tracks upstream presence and clears ahead after push", async () => {
    const origin = await mkdtemp(join(tmpdir(), "passage-git-origin-"));
    roots.push(origin);
    await git(origin, "init", "--bare");
    const root = await mkdtemp(join(tmpdir(), "passage-git-clone-"));
    roots.push(root);
    await git(root, "init", "-b", "main");
    await git(root, "config", "user.email", "test@example.com");
    await git(root, "config", "user.name", "Test");
    await git(root, "remote", "add", "origin", origin);
    await writeFile(join(root, "a.txt"), "a\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    const service = new GitService();
    expect((await service.status(root)).hasUpstream).toBe(false);
    await git(root, "push", "-u", "origin", "main");
    expect((await service.status(root)).hasUpstream).toBe(true);
    await writeFile(join(root, "b.txt"), "b\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "second");
    expect((await service.status(root)).ahead).toBe(1);
    await service.push(root);
    const after = await service.status(root);
    expect(after.hasUpstream).toBe(true);
    expect(after.ahead).toBe(0);
  });
  test("push sets upstream on first publish", async () => {
    const origin = await mkdtemp(join(tmpdir(), "passage-git-origin-"));
    roots.push(origin);
    await git(origin, "init", "--bare");
    const root = await mkdtemp(join(tmpdir(), "passage-git-clone-"));
    roots.push(root);
    await git(root, "init", "-b", "main");
    await git(root, "config", "user.email", "test@example.com");
    await git(root, "config", "user.name", "Test");
    await git(root, "remote", "add", "origin", origin);
    await writeFile(join(root, "a.txt"), "a\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "initial");
    const service = new GitService();
    expect((await service.status(root)).hasUpstream).toBe(false);
    await service.push(root);
    const after = await service.status(root);
    expect(after.hasUpstream).toBe(true);
    expect(after.ahead).toBe(0);
  });
  test("rebases a worktree branch onto the remote default", async () => {
    const origin = await mkdtemp(join(tmpdir(), "passage-git-origin-"));
    roots.push(origin);
    await git(origin, "init", "--bare");
    const root = await fixture();
    const service = new GitService();
    await git(root, "remote", "add", "origin", origin);
    await writeFile(join(root, "base.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "base");
    await git(root, "push", "-u", "origin", "main");
    const wt = join(root, "feature-wt");
    await git(root, "worktree", "add", "-b", "feature", wt);
    await writeFile(join(wt, "feature.txt"), "feature\n");
    await git(wt, "add", ".");
    await git(wt, "commit", "-m", "feature work");
    // Advance the remote after the branch was cut.
    await writeFile(join(root, "remote.txt"), "remote\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "remote progress");
    await git(root, "push", "origin", "main");
    expect(await service.remoteDefaultBranch(wt)).toBe("main");
    const rebased = await service.rebaseOntoRemote(wt);
    expect(rebased).toEqual({ remote: "origin", base: "main" });
    expect(await readFile(join(wt, "remote.txt"), "utf8")).toBe("remote\n");
    expect(await readFile(join(wt, "feature.txt"), "utf8")).toBe("feature\n");
  });
  test("rebase onto a missing remote branch fails cleanly", async () => {
    const root = await fixture();
    const service = new GitService();
    const wt = join(root, "feature-wt");
    await writeFile(join(root, "base.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "base");
    await git(root, "worktree", "add", "-b", "feature", wt);
    // No remotes at all: fetch fails fast with a GitError.
    await expect(service.rebaseOntoRemote(wt)).rejects.toBeInstanceOf(GitError);
    // Untracked-file guard: the failed rebase leaves no mid-rebase state.
    expect((await service.status(wt)).files.length).toBe(0);
  });
  test("describes a branch diff against its base for PRs", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "base.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "base");
    await git(root, "checkout", "-b", "feature");
    await writeFile(join(root, "feature.txt"), "feature\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "feature work");
    const preview = await service.branchDiffForPr(root);
    expect(preview.base).toBe("main");
    expect(preview.mergeBase).toMatch(/^[0-9a-f]{40}$/);
    expect(preview.files).toEqual([{ path: "feature.txt", kind: "added" }]);
    expect(preview.diff).toContain("+feature");
    expect(preview.truncated).toBe(false);
  });
  test("branch diff with no commits beyond base is empty", async () => {
    const root = await fixture();
    const service = new GitService();
    await writeFile(join(root, "base.txt"), "base\n");
    await git(root, "add", ".");
    await git(root, "commit", "-m", "base");
    const preview = await service.branchDiffForPr(root, "main");
    expect(preview.files).toEqual([]);
  });
});
