import { afterEach, describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, symlink, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { MetadataRepositories, MetadataStore } from "../metadata/index.ts";
import { WorkspaceError, WorkspaceService } from "./service.ts";

const roots: string[] = [];
async function fixture() { const root = await mkdtemp(join(tmpdir(), "passage-workspace-")); roots.push(root); const store = new MetadataStore(join(root, "metadata.sqlite")); const repositories = new MetadataRepositories(store.db); const service = new WorkspaceService(repositories, 3); return { root, store, service }; }
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
const fails = (promise: Promise<unknown>, code: WorkspaceError["code"]) => expect(promise).rejects.toMatchObject({ code });

describe("WorkspaceService", () => {
  test("persists, reloads, labels, archives, and reopens", async () => { const f = await fixture(); const project = await f.service.registerProject(f.root, "Project"); const workspace = await f.service.createDirectoryWorkspace(project.id, { displayLabel: "Work" }); f.service.labelWorkspace(workspace.id, "Renamed"); f.service.archiveWorkspace(workspace.id); expect(f.service.snapshot().workspaces[0].archivedAt).not.toBeNull(); f.service.reopenWorkspace(workspace.id); f.store.close(); const reopened = new MetadataStore(join(f.root, "metadata.sqlite")); const service = new WorkspaceService(new MetadataRepositories(reopened.db)); expect(service.snapshot().workspaces[0].displayLabel).toBe("Renamed"); reopened.close(); });
  test("supports nested cwd and rejects files and missing roots", async () => { const f = await fixture(); const nested = join(f.root, "nested"); await mkdir(nested); const file = join(f.root, "file"); await writeFile(file, "x"); const p = await f.service.registerProject(f.root, "P"); expect((await f.service.createDirectoryWorkspace(p.id, { cwd: "nested", displayLabel: "N" })).cwd).toBe(nested); await fails(f.service.registerProject(file, "bad"), "invalid-root"); await fails(f.service.resolvePath("missing", "x"), "not-found"); });
  test("discovers git and leaves non-git as directory metadata", async () => { const f = await fixture(); const repo = join(f.root, "repo"); await mkdir(repo); const run = Bun.spawn(["git", "-C", repo, "init"], { stdout: "ignore", stderr: "ignore" }); await run.exited; const p = await f.service.registerProject(repo, "R"); const w = await f.service.createDirectoryWorkspace(p.id, { displayLabel: "Git" }); expect(w.checkoutRoot).toBe(repo); const plain = await f.service.registerProject(f.root, "P"); expect((await f.service.createDirectoryWorkspace(plain.id, { displayLabel: "Plain" })).mainRepositoryRoot).toBeNull(); });
  test("enforces containment, symlinks, and valid dotted names", async () => { const f = await fixture(); const p = await f.service.registerProject(f.root, "P"); const w = await f.service.createDirectoryWorkspace(p.id, { displayLabel: "W" }); await writeFile(join(f.root, "name..txt"), "x"); expect(await f.service.resolvePath(w.id, "name..txt")).toBe(join(f.root, "name..txt")); await symlink(tmpdir(), join(f.root, "escape")); await fails(f.service.resolvePath(w.id, "../outside"), "outside-root"); await fails(f.service.resolvePath(w.id, join(tmpdir(), "outside")), "outside-root"); await fails(f.service.resolvePath(w.id, "escape"), "outside-root"); await fails(f.service.resolvePath(w.id, "missing"), "invalid-root"); });
  test("handles locations, archives, and bounds snapshots", async () => { const f = await fixture(); const p = await f.service.registerProject(f.root, "P"); const global = await f.service.configureLocation({ displayLabel: "Global", configuredRootPath: f.root }); const project = await f.service.configureLocation({ projectId: p.id, displayLabel: "Project", configuredRootPath: f.root }); expect(new Set(f.service.snapshot().locations.map((x) => x.id))).toEqual(new Set([global.id, project.id])); f.service.archiveProject(p.id); await fails(f.service.createDirectoryWorkspace(p.id, { displayLabel: "bad" }), "archived"); const w = await f.service.createDirectoryWorkspace(f.service.reopenProject(p.id).id, { displayLabel: "W" }); f.service.archiveWorkspace(w.id); await fails(f.service.resolvePath(w.id, "."), "archived"); expect(() => new WorkspaceService(new MetadataRepositories(f.store.db), 0)).toThrow(); });
});
