import { z } from "zod";

const colorRegex = /^#([0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$|^rgba?\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*(?:,\s*[\d.]+\s*)?\)$|^hsla?\(\s*[\d.]+\s*,\s*[\d.]+%?\s*,\s*[\d.]+%?\s*(?:,\s*[\d.]+\s*)?\)$/;

export const themeColorSchema = z.string().regex(colorRegex, "Must be a valid hex, rgb, or hsl color string");

export const themeTokensSchema = z.object({
  background: themeColorSchema,
  foreground: themeColorSchema,
  surface: themeColorSchema,
  surfaceSubtle: themeColorSchema.optional(),
  surfaceElevated: themeColorSchema.optional(),
  surfaceHover: themeColorSchema.optional(),
  surfaceSelected: themeColorSchema.optional(),
  border: themeColorSchema,
  borderStrong: themeColorSchema,
  accent: themeColorSchema,
  accentHover: themeColorSchema,
  accentSubtle: themeColorSchema.optional(),
  muted: themeColorSchema,
  statusRunning: themeColorSchema,
  statusIdle: themeColorSchema,
  statusError: themeColorSchema,
  statusWarning: themeColorSchema,
  userCardBg: themeColorSchema.optional(),
  userCardBorder: themeColorSchema.optional(),
  composerBg: themeColorSchema.optional(),
  composerBorder: themeColorSchema.optional(),
  chipBg: themeColorSchema.optional(),
  secondary: themeColorSchema.optional(),
  secondaryForeground: themeColorSchema.optional(),
  chipBlueBg: themeColorSchema.optional(),
  chipBlueFg: themeColorSchema.optional(),
  chipBlueBorder: themeColorSchema.optional(),
  diffAdd: themeColorSchema.optional(),
  diffAddSubtle: themeColorSchema.optional(),
  diffRemove: themeColorSchema.optional(),
  diffRemoveSubtle: themeColorSchema.optional(),
  diffHunk: themeColorSchema.optional(),
  diffHunkSubtle: themeColorSchema.optional(),
  terminalBackground: themeColorSchema.optional(),
  terminalForeground: themeColorSchema.optional(),
  editorBackground: themeColorSchema.optional(),
});
export type ThemeTokens = z.infer<typeof themeTokensSchema>;

export const themePackSchema = z.object({
  id: z.string().min(1).max(64).regex(/^[a-z0-9-]+$/),
  name: z.string().min(1).max(64),
  mode: z.enum(["dark", "light", "system"]),
  tokens: themeTokensSchema,
});
export type ThemePack = z.infer<typeof themePackSchema>;

export const fontPackSchema = z.object({
  id: z.string().min(1).max(64).regex(/^[a-z0-9-]+$/),
  name: z.string().min(1).max(64),
  uiFontFamily: z.string().min(1).max(256),
  monoFontFamily: z.string().min(1).max(256),
  editorFontFamily: z.string().min(1).max(256),
});
export type FontPack = z.infer<typeof fontPackSchema>;

export const toolMatcherSchema = z.object({
  toolName: z.string().min(1).max(64),
  displayName: z.string().min(1).max(64).optional(),
  icon: z.string().min(1).max(32).optional(),
  summaryTemplate: z.string().min(1).max(256).optional(),
  category: z.enum(["file", "git", "command", "agent", "search", "generic"]).default("generic"),
  showInConcise: z.boolean().default(true),
});
export type ToolMatcher = z.infer<typeof toolMatcherSchema>;

export const toolRendererPackSchema = z.object({
  id: z.string().min(1).max(64).regex(/^[a-z0-9-]+$/),
  name: z.string().min(1).max(64),
  matchers: z.array(toolMatcherSchema).max(50),
});
export type ToolRendererPack = z.infer<typeof toolRendererPackSchema>;

// Built-in theme packs
export const BUILTIN_THEMES: ThemePack[] = [
  {
    id: "passage-light",
    name: "Passage Warm Light (Default)",
    mode: "light",
    tokens: {
      background: "#fdfcfa",
      foreground: "#393a34",
      surface: "#ffffff",
      surfaceSubtle: "#f5f1ea",
      surfaceElevated: "#f5f1ea",
      surfaceHover: "#ebe6dc",
      surfaceSelected: "#e2dcce",
      border: "#e7e2d7",
      borderStrong: "#cfc7ba",
      accent: "#0f766e",
      accentHover: "#115e59",
      accentSubtle: "#ccfbf1",
      muted: "#82877d",
      statusRunning: "#d97706",
      statusIdle: "#6b7280",
      statusError: "#b91c1c",
      statusWarning: "#d97706",
      userCardBg: "#f6f2ea",
      userCardBorder: "#e7e2d7",
      composerBg: "#ffffff",
      composerBorder: "#e7e2d7",
      chipBg: "#ece7de",
      secondary: "#ece7de",
      secondaryForeground: "#393a34",
      chipBlueBg: "#e0f2fe",
      chipBlueFg: "#0369a1",
      chipBlueBorder: "#bfdbfe",
      diffAdd: "#15803d",
      diffAddSubtle: "#ecfdf5",
      diffRemove: "#b91c1c",
      diffRemoveSubtle: "#fef2f2",
      diffHunk: "#0369a1",
      diffHunkSubtle: "#f0f9ff",
      terminalBackground: "#191c1e",
      terminalForeground: "#ecebe8",
      editorBackground: "#ffffff",
    },
  },
  {
    id: "passage-dark",
    name: "Passage Charcoal Dark",
    mode: "dark",
    tokens: {
      background: "#141618",
      foreground: "#ecebe8",
      surface: "#1c1f22",
      surfaceSubtle: "#23272b",
      surfaceElevated: "#282d33",
      surfaceHover: "#2c3136",
      surfaceSelected: "#353b42",
      border: "#2e3339",
      borderStrong: "#444b54",
      accent: "#14b8a6",
      accentHover: "#2dd4bf",
      accentSubtle: "#134e48",
      muted: "#9aa0a6",
      statusRunning: "#f59e0b",
      statusIdle: "#9aa0a6",
      statusError: "#ef4444",
      statusWarning: "#f59e0b",
      userCardBg: "#23272c",
      userCardBorder: "#2e3339",
      composerBg: "#1c1f22",
      composerBorder: "#2e3339",
      chipBg: "#2a2f35",
      secondary: "#282d33",
      secondaryForeground: "#ecebe8",
      chipBlueBg: "#162a3d",
      chipBlueFg: "#38bdf8",
      chipBlueBorder: "rgba(56, 189, 248, 0.3)",
      diffAdd: "#22c55e",
      diffAddSubtle: "#0d2818",
      diffRemove: "#ef4444",
      diffRemoveSubtle: "#2d1215",
      diffHunk: "#38bdf8",
      diffHunkSubtle: "#0c2438",
      terminalBackground: "#141618",
      terminalForeground: "#ecebe8",
      editorBackground: "#1c1f22",
    },
  },
  {
    id: "nord",
    name: "Nord",
    mode: "dark",
    tokens: {
      background: "#2e3440",
      foreground: "#eceff4",
      surface: "#3b4252",
      surfaceSubtle: "#434c5e",
      surfaceElevated: "#434c5e",
      surfaceHover: "#4c566a",
      surfaceSelected: "#4c566a",
      border: "#4c566a",
      borderStrong: "#d8dee9",
      accent: "#88c0d0",
      accentHover: "#81a1c1",
      accentSubtle: "#3b4252",
      muted: "#d8dee9",
      statusRunning: "#a3be8c",
      statusIdle: "#9aa0a6",
      statusError: "#bf616a",
      statusWarning: "#ebcb8b",
      userCardBg: "#3b4252",
      userCardBorder: "#4c566a",
      composerBg: "#3b4252",
      composerBorder: "#4c566a",
      chipBg: "#434c5e",
      secondary: "#434c5e",
      secondaryForeground: "#eceff4",
      chipBlueBg: "#2e3b4d",
      chipBlueFg: "#88c0d0",
      chipBlueBorder: "rgba(136, 192, 208, 0.3)",
      diffAdd: "#a3be8c",
      diffAddSubtle: "#2e3b32",
      diffRemove: "#bf616a",
      diffRemoveSubtle: "#3b2e30",
      diffHunk: "#88c0d0",
      diffHunkSubtle: "#2e3840",
      terminalBackground: "#2e3440",
      terminalForeground: "#eceff4",
      editorBackground: "#2e3440",
    },
  },
  {
    id: "high-contrast-dark",
    name: "High Contrast Dark",
    mode: "dark",
    tokens: {
      background: "#000000",
      foreground: "#ffffff",
      surface: "#121212",
      surfaceSubtle: "#1e1e1e",
      surfaceElevated: "#1e1e1e",
      surfaceHover: "#2a2a2a",
      surfaceSelected: "#333333",
      border: "#404040",
      borderStrong: "#ffffff",
      accent: "#00e5ff",
      accentHover: "#18ffff",
      accentSubtle: "#00363a",
      muted: "#a0a0a0",
      statusRunning: "#00e676",
      statusIdle: "#a0a0a0",
      statusError: "#ff1744",
      statusWarning: "#ffd600",
      userCardBg: "#181818",
      userCardBorder: "#404040",
      composerBg: "#121212",
      composerBorder: "#404040",
      chipBg: "#222222",
      secondary: "#1e1e1e",
      secondaryForeground: "#ffffff",
      chipBlueBg: "#00363a",
      chipBlueFg: "#00e5ff",
      chipBlueBorder: "rgba(0, 229, 255, 0.4)",
      diffAdd: "#00e676",
      diffAddSubtle: "#002914",
      diffRemove: "#ff1744",
      diffRemoveSubtle: "#290008",
      diffHunk: "#00e5ff",
      diffHunkSubtle: "#002024",
      terminalBackground: "#000000",
      terminalForeground: "#ffffff",
      editorBackground: "#000000",
    },
  },
];

// Built-in font packs
export const BUILTIN_FONTS: FontPack[] = [
  {
    id: "system-default",
    name: "System Default",
    uiFontFamily: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    monoFontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    editorFontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
  {
    id: "fira-code",
    name: "Fira Code",
    uiFontFamily: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    monoFontFamily: "'Fira Code', ui-monospace, monospace",
    editorFontFamily: "'Fira Code', ui-monospace, monospace",
  },
  {
    id: "jetbrains-mono",
    name: "JetBrains Mono",
    uiFontFamily: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    monoFontFamily: "'JetBrains Mono', ui-monospace, monospace",
    editorFontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
];

// Built-in tool renderer pack
export const BUILTIN_TOOL_RENDERERS: ToolRendererPack = {
  id: "builtin",
  name: "Default Tool Renderers",
  matchers: [
    { toolName: "read", displayName: "Read", icon: "📖", category: "file", showInConcise: true },
    { toolName: "edit", displayName: "Edit", icon: "✏️", category: "file", showInConcise: true },
    { toolName: "write", displayName: "Write", icon: "📝", category: "file", showInConcise: true },
    { toolName: "bash", displayName: "Ran", icon: "⚡", category: "command", showInConcise: true },
    { toolName: "glob", displayName: "Search files", icon: "🔍", category: "search", showInConcise: true },
    { toolName: "grep", displayName: "Search text", icon: "🔎", category: "search", showInConcise: true },
    { toolName: "git", displayName: "Git", icon: "±", category: "git", showInConcise: true },
  ],
};
